workdir: /home/debian/NGS/dev/GMO/test
samples: /home/debian/NGS/dev/GMO/fastq/samples.tsv
threads_sample: 8 # quite critical for mapping. RAM footprint is big (30Gb per sample?) so maximize CPU usage by making one sample at a time. 

# genomes: /home/debian/NGS/dev/GMO/references/genomes.tsv (BWA indexed)
indexed_ref: /home/debian/NGS/dev/GMO/references/merged_refs.fa
# panel fasta file
panel: /home/debian/NGS/dev/GMO/panel/gmo_feed_panel_v2_ongoing.fa
# event specific sequences as fasta
event_detection: /home/debian/NGS/dev/GMO/event_detection/event_detection_soja.fa

# Trimming parameters
read_length_required: 50
qualified_quality_phred: 15
qctrim_window_size: 4
qctrim_mean_quality: 30

# UMI/MBC detection (Agilent only)
umi: True
umi_loc: per_read 
umi_len: 3

# Mapping parameters (host)

# Assembly parameters (SAUTE)
assembly_kmer_min_count: 1 # Default=2
assembly_noise_to_signal: 0.05 # Default=0.05

# BLAST parameters

# Mapping parameters (contigs)